#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/index.pug -> dist/index.html ..."
npx srcbuild-pug src/index.pug -o dist/index.html
./node_modules/.bin/lsc -cp --no-header src/index.ls > dist/index.js

echo "done."
